package com.tivic.manager.util.cdi;



import com.tivic.manager.arquivos.repository.FileSystemRepository;
import com.tivic.manager.arquivos.repository.IFileSystemRepository;
import com.tivic.manager.conf.ManagerConf;
import com.tivic.manager.fix.mob.ait.cidade.FixCidadeService;
import com.tivic.manager.fix.mob.ait.cidade.IFixCidadeService;
import com.tivic.manager.fix.mob.ait.infracao.FixInfracaoAitService;
import com.tivic.manager.fix.mob.ait.infracao.IFixInfracaoAitService;
import com.tivic.manager.fix.mob.ait.proprietario.FixProprietarioAitService;
import com.tivic.manager.fix.mob.ait.proprietario.IFixProprietarioAitService;
import com.tivic.manager.fix.mob.ait.task.ClientFixEnderecoNotificacao;
import com.tivic.manager.fix.mob.ait.task.IClientFixEnderecoNotificacao;
import com.tivic.manager.fta.categoriaveiculo.CategoriaVeiculoRepository;
import com.tivic.manager.fta.categoriaveiculo.CategoriaVeiculoRepositoryDAO;
import com.tivic.manager.fta.cor.CorRepository;
import com.tivic.manager.fta.cor.CorRepositoryDAO;
import com.tivic.manager.fta.cor.CorService;
import com.tivic.manager.fta.cor.ICorService;
import com.tivic.manager.fta.especieveiculo.EspecieVeiculoRepository;
import com.tivic.manager.fta.especieveiculo.EspecieVeiculoRepositoryDAO;
import com.tivic.manager.fta.especieveiculo.EspecieVeiculoService;
import com.tivic.manager.fta.especieveiculo.IEspecieVeiculoService;
import com.tivic.manager.fta.marcamodelo.IMarcaModeloService;
import com.tivic.manager.fta.marcamodelo.MarcaModeloRepository;
import com.tivic.manager.fta.marcamodelo.MarcaModeloRepositoryDAO;
import com.tivic.manager.fta.marcamodelo.MarcaModeloService;
import com.tivic.manager.fta.tipoveiculo.ITipoVeiculoService;
import com.tivic.manager.fta.tipoveiculo.TipoVeiculoRepository;
import com.tivic.manager.fta.tipoveiculo.TipoVeiculoRepositoryDAO;
import com.tivic.manager.fta.tipoveiculo.TipoVeiculoService;
import com.tivic.manager.grl.IPessoaArquivoRepository;
import com.tivic.manager.grl.IPessoaEmpresaRepository;
import com.tivic.manager.grl.IPessoaEnderecoRepository;
import com.tivic.manager.grl.IPessoaFisicaRepository;
import com.tivic.manager.grl.IPessoaRepository;
import com.tivic.manager.grl.PessoaArquivoRepository;
import com.tivic.manager.grl.PessoaEmpresaRepositoryDAO;
import com.tivic.manager.grl.PessoaEnderecoRepositoryDAO;
import com.tivic.manager.grl.PessoaFisicaRepositoryDAO;
import com.tivic.manager.grl.PessoaRepositoryDAO;
import com.tivic.manager.grl.arquivo.ArquivoRepositoryDAO;
import com.tivic.manager.grl.arquivo.ArquivoService;
import com.tivic.manager.grl.arquivo.IArquivoRepository;
import com.tivic.manager.grl.arquivo.IArquivoService;
import com.tivic.manager.grl.bairro.BairroRepository;
import com.tivic.manager.grl.bairro.BairroRepositoryDAO;
import com.tivic.manager.grl.banco.BancoService;
import com.tivic.manager.grl.banco.IBancoService;
import com.tivic.manager.grl.banco.repository.BancoRepository;
import com.tivic.manager.grl.banco.repository.BancoRepositoryDAO;
import com.tivic.manager.grl.cidade.CidadeRepository;
import com.tivic.manager.grl.cidade.CidadeRepositoryDAO;
import com.tivic.manager.grl.cidade.CidadeService;
import com.tivic.manager.grl.cidade.ICidadeService;
import com.tivic.manager.grl.cidade.cidadeproprietario.CorretorIDCidade;
import com.tivic.manager.grl.cidade.cidadeproprietario.ICorretorIDCidade;
import com.tivic.manager.grl.equipamento.EquipamentoService;
import com.tivic.manager.grl.equipamento.IEquipamentoService;
import com.tivic.manager.grl.equipamento.radar.v3.IRadarService;
import com.tivic.manager.grl.equipamento.radar.v3.RadarService;
import com.tivic.manager.grl.equipamento.repository.EquipamentoRepository;
import com.tivic.manager.grl.equipamento.repository.EquipamentoRepositoryDAO;
import com.tivic.manager.grl.estado.EstadoRepository;
import com.tivic.manager.grl.estado.EstadoRepositoryDAO;
import com.tivic.manager.grl.pais.PaisRepository;
import com.tivic.manager.grl.pais.PaisRepositoryDAO;
import com.tivic.manager.grl.parametro.IParametroService;
import com.tivic.manager.grl.parametro.ParametroService;
import com.tivic.manager.grl.parametro.repository.IParametroRepository;
import com.tivic.manager.grl.parametro.repository.ParametroRepositoryDAOFactory;
import com.tivic.manager.grl.parametrovalor.ParametroValorRepository;
import com.tivic.manager.grl.parametrovalor.ParametroValorRepositoryDAO;
import com.tivic.manager.grl.pessoaempresa.IPessoaEmpresaService;
import com.tivic.manager.grl.pessoaempresa.PessoaEmpresaService;
import com.tivic.manager.grl.pessoafisica.IPessoaFisicaService;
import com.tivic.manager.grl.pessoafisica.PessoaFisicaService;
import com.tivic.manager.grl.pessoavinculohistorico.IPessoaVinculoHistoricoService;
import com.tivic.manager.grl.pessoavinculohistorico.PessoaVinculoHistoricoService;
import com.tivic.manager.grl.pessoavinculohistorico.repository.PessoaVinculoHistoricoRepository;
import com.tivic.manager.grl.pessoavinculohistorico.repository.PessoaVinculoHistoricoRepositoryDAO;
import com.tivic.manager.grl.tipoarquivo.ITipoArquivoRepository;
import com.tivic.manager.grl.tipoarquivo.ITipoArquivoService;
import com.tivic.manager.grl.tipoarquivo.TipoArquivoRepositoryDAO;
import com.tivic.manager.grl.tipoarquivo.TipoArquivoService;
import com.tivic.manager.grl.vinculo.IVinculoService;
import com.tivic.manager.grl.vinculo.VinculoRepository;
import com.tivic.manager.grl.vinculo.VinculoRepositoryDAO;
import com.tivic.manager.grl.vinculo.VinculoService;
import com.tivic.manager.mob.AitMovimentoDocumentoServices;
import com.tivic.manager.mob.AitReportServicesNip;
import com.tivic.manager.mob.AitReportValidatorsNIP;
import com.tivic.manager.mob.CorreiosEtiquetaServices;
import com.tivic.manager.mob.acaousuario.AcaoUsuarioRepository;
import com.tivic.manager.mob.acaousuario.AcaoUsuarioRepositoryDAO;
import com.tivic.manager.mob.acaousuario.AcaoUsuarioService;
import com.tivic.manager.mob.acaousuario.IAcaoUsuarioService;
import com.tivic.manager.mob.agente.AgenteRepository;
import com.tivic.manager.mob.agente.AgenteRepositoryFactory;
import com.tivic.manager.mob.agente.AgenteService;
import com.tivic.manager.mob.agente.IAgenteService;
import com.tivic.manager.mob.ait.AitRepository;
import com.tivic.manager.mob.ait.AitRepositoryFactory;
import com.tivic.manager.mob.ait.AitService;
import com.tivic.manager.mob.ait.IAitService;
import com.tivic.manager.mob.ait.aitArquivo.AitArquivoRepositoryDAO;
import com.tivic.manager.mob.ait.aitArquivo.IAitArquivoRepository;
import com.tivic.manager.mob.ait.aitimagempessoa.AitImagemPessoaRepository;
import com.tivic.manager.mob.ait.aitimagempessoa.AitImagemPessoaRepositoryDAO;
import com.tivic.manager.mob.ait.aitimagempessoa.AitImagemPessoaService;
import com.tivic.manager.mob.ait.aitimagempessoa.IAitImagemPessoaService;
import com.tivic.manager.mob.ait.aitpessoa.AitPessoaRepository;
import com.tivic.manager.mob.ait.aitpessoa.AitPessoaRepositoryDAO;
import com.tivic.manager.mob.ait.aitpessoa.AitPessoaService;
import com.tivic.manager.mob.ait.aitpessoa.IAitPessoaService;
import com.tivic.manager.mob.ait.cancelamento.AitCancelamentoRepositoryDAO;
import com.tivic.manager.mob.ait.cancelamento.IAitCancelamentoRepository;
import com.tivic.manager.mob.ait.circuitoait.CircuitoAit;
import com.tivic.manager.mob.ait.imagemvideo.aitvideo.AitVideoService;
import com.tivic.manager.mob.ait.imagemvideo.aitvideo.IAitVideoService;
import com.tivic.manager.mob.ait.relatorios.GeraRelatorioAitSne;
import com.tivic.manager.mob.ait.relatorios.GeraSegundaViaNaiService;
import com.tivic.manager.mob.ait.relatorios.IGeraRelatorioAitSne;
import com.tivic.manager.mob.ait.relatorios.IGeraSegundaViaNaiService;
import com.tivic.manager.mob.ait.relatorios.IRelatorioAitCompetenciaEstadual;
import com.tivic.manager.mob.ait.relatorios.IRelatorioRecursoServices;
import com.tivic.manager.mob.ait.relatorios.RelatorioAitCompetenciaEstadual;
import com.tivic.manager.mob.ait.relatorios.RelatorioRecursoServices;
import com.tivic.manager.mob.ait.relatorios.quantitativo.IRelatorioQuantitativoService;
import com.tivic.manager.mob.ait.relatorios.quantitativo.RelatorioQuantitativoService;
import com.tivic.manager.mob.ait.sync.AitPessoaSyncService;
import com.tivic.manager.mob.ait.sync.AitSyncService;
import com.tivic.manager.mob.ait.sync.AitSyncTools;
import com.tivic.manager.mob.ait.sync.AtualizaTalonarioAit;
import com.tivic.manager.mob.ait.sync.AtualizaTalonarioAitPessoa;
import com.tivic.manager.mob.ait.sync.IAitPessoaSyncService;
import com.tivic.manager.mob.ait.sync.IAitSyncService;
import com.tivic.manager.mob.ait.sync.IAitSyncTools;
import com.tivic.manager.mob.ait.sync.IAtualizaTalonarioAit;
import com.tivic.manager.mob.ait.sync.IAtualizaTalonarioAitPessoa;
import com.tivic.manager.mob.ait.sync.observer.AitSyncSubject;
import com.tivic.manager.mob.ait.sync.observer.IAitSyncObserver;
import com.tivic.manager.mob.ait.sync.observer.IAitSyncSubject;
import com.tivic.manager.mob.ait.sync.observer.ImageConversionObserver;
import com.tivic.manager.mob.ait.validacao.IValidacaoAitPendente;
import com.tivic.manager.mob.ait.validacao.ValidacaoAitPendente;
import com.tivic.manager.mob.aitevento.AitEventoRepository;
import com.tivic.manager.mob.aitevento.AitEventoRepositoryDAO;
import com.tivic.manager.mob.aitevento.AitEventoService;
import com.tivic.manager.mob.aitevento.IAitEventoService;
import com.tivic.manager.mob.aitimagem.AitImagemService;
import com.tivic.manager.mob.aitimagem.IAitImagemService;
import com.tivic.manager.mob.aitimagem.repositories.AitImagemRepositoryFactory;
import com.tivic.manager.mob.aitimagem.repositories.IAitImagemRepository;
import com.tivic.manager.mob.aitimagem.task.ClientConversorImagemTask;
import com.tivic.manager.mob.aitimagem.task.IClientConversorImagemTask;
import com.tivic.manager.mob.aitimagem.task.IImageReencoder;
import com.tivic.manager.mob.aitimagem.task.ImageReencoder;
import com.tivic.manager.mob.aitmovimento.AitMovimentoRepository;
import com.tivic.manager.mob.aitmovimento.AitMovimentoRepositoryFactory;
import com.tivic.manager.mob.aitmovimento.AitMovimentoService;
import com.tivic.manager.mob.aitmovimento.IAitMovimentoService;
import com.tivic.manager.mob.aitmovimento.calculomediamovimento.CalculoMediaMovimentoService;
import com.tivic.manager.mob.aitmovimento.calculomediamovimento.ICalculoMediaMovimentoService;
import com.tivic.manager.mob.aitmovimento.cancelamentomovimentos.CancelaRevertePenalidade;
import com.tivic.manager.mob.aitmovimento.cancelamentomovimentos.ICancelaRevertePenalidade;
import com.tivic.manager.mob.aitmovimento.task.ClientEnvioRegistroInfracaoTask;
import com.tivic.manager.mob.aitmovimento.task.IClientEnvioRegistroInfracaoTask;
import com.tivic.manager.mob.aitmovimentodocumento.AitMovimentoDocumentoRepository;
import com.tivic.manager.mob.aitmovimentodocumento.AitMovimentoDocumentoRepositoryDAO;
import com.tivic.manager.mob.aitmovimentodocumento.AitMovimentoDocumentoService;
import com.tivic.manager.mob.aitmovimentodocumento.IAitMovimentoDocumentoService;
import com.tivic.manager.mob.aitpagamento.AitPagamentoRepository;
import com.tivic.manager.mob.aitpagamento.AitPagamentoRepositoryDAO;
import com.tivic.manager.mob.aitpagamento.AitPagamentoService;
import com.tivic.manager.mob.aitpagamento.IAitPagamentoService;
import com.tivic.manager.mob.arquivomovimento.ArquivoMovimentoRepository;
import com.tivic.manager.mob.arquivomovimento.ArquivoMovimentoRepositoryDAO;
import com.tivic.manager.mob.arquivomovimento.ArquivoMovimentoService;
import com.tivic.manager.mob.arquivomovimento.IArquivoMovimentoService;
import com.tivic.manager.mob.boat.repository.BoatRepository;
import com.tivic.manager.mob.boat.repository.BoatRepositoryDAO;
import com.tivic.manager.mob.colaborador.ColaboradorService;
import com.tivic.manager.mob.colaborador.IColaboradorService;
import com.tivic.manager.mob.convenio.ConvenioRepository;
import com.tivic.manager.mob.convenio.ConvenioRepositoryDAO;
import com.tivic.manager.mob.convenio.ConvenioService;
import com.tivic.manager.mob.convenio.IConvenioService;
import com.tivic.manager.mob.convenio.IMudaConvenioDefault;
import com.tivic.manager.mob.convenio.MudaConvenioDefault;
import com.tivic.manager.mob.correios.CorreiosEtiquetaRepositoryDAO;
import com.tivic.manager.mob.correios.CorreiosEtiquetaService;
import com.tivic.manager.mob.correios.CorreiosLoteRepository;
import com.tivic.manager.mob.correios.CorreiosLoteRepositoryDAO;
import com.tivic.manager.mob.correios.CorreiosLoteService;
import com.tivic.manager.mob.correios.FTPSService;
import com.tivic.manager.mob.correios.ICorreiosEtiquetaRepository;
import com.tivic.manager.mob.correios.ICorreiosEtiquetaService;
import com.tivic.manager.mob.correios.ICorreiosLoteService;
import com.tivic.manager.mob.correios.IFTPSService;
import com.tivic.manager.mob.ecarta.ECartasService;
import com.tivic.manager.mob.ecarta.IEcartasService;
import com.tivic.manager.mob.ecarta.services.ArquivoProducaoServiceEDI;
import com.tivic.manager.mob.ecarta.services.ArquivoRetornoServiceEDI;
import com.tivic.manager.mob.ecarta.services.ArquivoServiceEDI;
import com.tivic.manager.mob.ecarta.services.AtualizaLoteImpressaoECT;
import com.tivic.manager.mob.ecarta.services.IArquivoProducaoServiceEDI;
import com.tivic.manager.mob.ecarta.services.IArquivoRetornoServiceEDI;
import com.tivic.manager.mob.ecarta.services.IArquivoServiceEDI;
import com.tivic.manager.mob.ecarta.services.IAtualizaLoteImpressaoECT;
import com.tivic.manager.mob.edat.EDatService;
import com.tivic.manager.mob.edat.IEDatService;
import com.tivic.manager.mob.edat.repositories.ITermosECondicoesRepository;
import com.tivic.manager.mob.edat.repositories.ITermosECondicoesService;
import com.tivic.manager.mob.edat.repositories.TermosECondicoesRepositoryDAO;
import com.tivic.manager.mob.edat.service.TermosECondicoesService;
import com.tivic.manager.mob.eventoarquivo.EventoArquivoRepository;
import com.tivic.manager.mob.eventoarquivo.EventoArquivoRepositoryDAO;
import com.tivic.manager.mob.eventoarquivo.EventoArquivoService;
import com.tivic.manager.mob.eventoarquivo.IEventoArquivoService;
import com.tivic.manager.mob.eventoequipamento.EventoEquipamentoRepository;
import com.tivic.manager.mob.eventoequipamento.EventoEquipamentoRepositoryDAO;
import com.tivic.manager.mob.eventoequipamento.EventoEquipamentoService;
import com.tivic.manager.mob.eventoequipamento.IEventoEquipamentoService;
import com.tivic.manager.mob.funset.FunsetBuscaAits;
import com.tivic.manager.mob.funset.FunsetInfos;
import com.tivic.manager.mob.funset.FunsetService;
import com.tivic.manager.mob.funset.IFunsetService;
import com.tivic.manager.mob.guiapagamento.GuiaPagamentoService;
import com.tivic.manager.mob.guiapagamento.IGuiaPagamentoService;
import com.tivic.manager.mob.guiapagamento.geraguiapagamento.GeraGuiaPagamento;
import com.tivic.manager.mob.guiapagamento.geraguiapagamento.IGeraGuiaPagamento;
import com.tivic.manager.mob.inconsistencias.AitInconsistenciaRepository;
import com.tivic.manager.mob.inconsistencias.AitInconsistenciaRepositoryDAO;
import com.tivic.manager.mob.inconsistencias.AitInconsistenciaService;
import com.tivic.manager.mob.inconsistencias.IAitInconsistenciaService;
import com.tivic.manager.mob.inconsistencias.IInconsistenciaService;
import com.tivic.manager.mob.inconsistencias.InconsistenciaRepository;
import com.tivic.manager.mob.inconsistencias.InconsistenciaRepositoryDAO;
import com.tivic.manager.mob.inconsistencias.InconsistenciaService;
import com.tivic.manager.mob.infracao.IInfracaoService;
import com.tivic.manager.mob.infracao.InfracaoRepository;
import com.tivic.manager.mob.infracao.InfracaoRepositoryFactory;
import com.tivic.manager.mob.infracao.InfracaoService;
import com.tivic.manager.mob.infracao.observacao.IInfracaoObservacaoService;
import com.tivic.manager.mob.infracao.observacao.InfracaoObservacaoRepository;
import com.tivic.manager.mob.infracao.observacao.InfracaoObservacaoRepositoryDAO;
import com.tivic.manager.mob.infracao.observacao.InfracaoObservacaoService;
import com.tivic.manager.mob.listagempagamentos.GeraRelatorioListagemPagamentos;
import com.tivic.manager.mob.listagempagamentos.IGeraRelatorioListagemPagamentos;
import com.tivic.manager.mob.listagempagamentos.IListagemPagamentosService;
import com.tivic.manager.mob.listagempagamentos.ListagemPagamentosService;
import com.tivic.manager.mob.lote.impressao.ClientNotificacaoTask;
import com.tivic.manager.mob.lote.impressao.IClientNotificacaoTask;
import com.tivic.manager.mob.lote.impressao.ILoteImpressaoAitRepository;
import com.tivic.manager.mob.lote.impressao.ILoteImpressaoArquivoRepository;
import com.tivic.manager.mob.lote.impressao.ILoteImpressaoRepository;
import com.tivic.manager.mob.lote.impressao.ILoteNotificacaoAitService;
import com.tivic.manager.mob.lote.impressao.ILoteNotificacaoService;
import com.tivic.manager.mob.lote.impressao.LoteImpressaoAitRepositoryDAO;
import com.tivic.manager.mob.lote.impressao.LoteImpressaoArquivoRepositoryDAO;
import com.tivic.manager.mob.lote.impressao.LoteImpressaoFactory;
import com.tivic.manager.mob.lote.impressao.LoteNotificacaoAitService;
import com.tivic.manager.mob.lote.impressao.LoteNotificacaoService;
import com.tivic.manager.mob.lote.impressao.dadosnotificacao.DadosNotificacaoFactory;
import com.tivic.manager.mob.lote.impressao.dadosnotificacao.IDadosNotificacaoService;
import com.tivic.manager.mob.lote.impressao.geracaodocumento.GeracaoDocumentosSSE;
import com.tivic.manager.mob.lote.impressao.geracaodocumento.IGeracaoDocumentosSSE;
import com.tivic.manager.mob.lote.impressao.lotedocumentoexterno.ILoteDocumentoExternoService;
import com.tivic.manager.mob.lote.impressao.lotedocumentoexterno.LoteDocumentoExternoRepository;
import com.tivic.manager.mob.lote.impressao.lotedocumentoexterno.LoteDocumentoExternoRepositoryDAO;
import com.tivic.manager.mob.lote.impressao.lotedocumentoexterno.LoteDocumentoExternoService;
import com.tivic.manager.mob.lote.impressao.publicacao.IPublicacaoNotificacaoService;
import com.tivic.manager.mob.lote.impressao.publicacao.PublicacaoNotificacaoService;
import com.tivic.manager.mob.lote.impressao.publicacao.service.ClientPublicacaoNotificacaoTask;
import com.tivic.manager.mob.lote.impressao.publicacao.service.IClientPublicacaoNotificacaoTask;
import com.tivic.manager.mob.lote.impressao.publicacao.task.ClientPublicacaoJariTask;
import com.tivic.manager.mob.lote.impressao.publicacao.task.IClientPublicacaoJariTask;
import com.tivic.manager.mob.lote.impressao.viaunica.nic.task.ClientGeracaoNicTask;
import com.tivic.manager.mob.lote.impressao.viaunica.nic.task.IClientGeracaoNicTask;
import com.tivic.manager.mob.lotes.movimento.IVerificaInfracaoAdvertencia;
import com.tivic.manager.mob.lotes.movimento.VerificaInfracaoAdvertencia;
import com.tivic.manager.mob.lotes.repository.LoteRepository;
import com.tivic.manager.mob.lotes.repository.LoteRepositoryDAO;
import com.tivic.manager.mob.lotes.repository.dividaativa.LoteDividaAtivaAitRepository;
import com.tivic.manager.mob.lotes.repository.dividaativa.LoteDividaAtivaAitRepositoryDAO;
import com.tivic.manager.mob.lotes.repository.dividaativa.LoteDividaAtivaRepository;
import com.tivic.manager.mob.lotes.repository.dividaativa.LoteDividaAtivaRepositoryDAO;
import com.tivic.manager.mob.lotes.service.dividaativa.ConfirmaLoteDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.GeraArquivoDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.GeraLoteDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.IConfirmaLoteDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.IGeraArquivoDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.IGeraLoteDividaAtiva;
import com.tivic.manager.mob.lotes.service.dividaativa.ILoteDividaAtivaService;
import com.tivic.manager.mob.lotes.service.dividaativa.LoteDividaAtivaService;
import com.tivic.manager.mob.mobile.EquipamentoTalonarioService;
import com.tivic.manager.mob.mobile.IEquipamentoTalonarioService;
import com.tivic.manager.mob.ocorrencia.IOcorrenciaService;
import com.tivic.manager.mob.ocorrencia.OcorrenciaRepository;
import com.tivic.manager.mob.ocorrencia.OcorrenciaRepositoryDAO;
import com.tivic.manager.mob.ocorrencia.OcorrenciaService;
import com.tivic.manager.mob.orgao.CidadeOrgaoResolver;
import com.tivic.manager.mob.orgao.IOrgaoService;
import com.tivic.manager.mob.orgao.OrgaoRepository;
import com.tivic.manager.mob.orgao.OrgaoRepositoryDAO;
import com.tivic.manager.mob.orgao.OrgaoService;
import com.tivic.manager.mob.orgaoaquivo.IOrgaoArquivoService;
import com.tivic.manager.mob.orgaoaquivo.OrgaoArquivoService;
import com.tivic.manager.mob.orgaoaquivo.repository.OrgaoArquivoRepository;
import com.tivic.manager.mob.orgaoaquivo.repository.OrgaoArquivoRepositoryDAO;
import com.tivic.manager.mob.orgaoexterno.IOrgaoExternoService;
import com.tivic.manager.mob.orgaoexterno.OrgaoExternoRepository;
import com.tivic.manager.mob.orgaoexterno.OrgaoExternoRepositoryDAO;
import com.tivic.manager.mob.orgaoexterno.OrgaoExternoService;
import com.tivic.manager.mob.pagamento.IRealizaPagamento;
import com.tivic.manager.mob.pagamento.RealizaPagamento;
import com.tivic.manager.mob.pessoa.PessoaRepository;
import com.tivic.manager.mob.pessoa.juridica.PessoaJuridicaRepository;
import com.tivic.manager.mob.pessoa.juridica.PessoaJuridicaRepositoryDAO;
import com.tivic.manager.mob.processamento.conversao.ConversaoEventoService;
import com.tivic.manager.mob.processamento.conversao.IConversaoEventoService;
import com.tivic.manager.mob.processamento.conversao.factories.conversao.ConversorBaseAntigaNovaFactory;
import com.tivic.manager.mob.processamento.conversao.services.ConversorEventoService;
import com.tivic.manager.mob.processamento.conversao.services.IConversorEventoService;
import com.tivic.manager.mob.processamento.conversao.tasks.ConversaoEventosTask;
import com.tivic.manager.mob.processamento.conversao.tasks.IConversaoEventosTask;
import com.tivic.manager.mob.processamento.sincronizacao.ISincronizacaoService;
import com.tivic.manager.mob.processamento.sincronizacao.SincronizacaoService;
import com.tivic.manager.mob.processamento.sincronizacao.services.EventoRadarHandlerService;
import com.tivic.manager.mob.processamento.sincronizacao.services.IEventoRadarHandlerService;
import com.tivic.manager.mob.processamento.sincronizacao.tasks.ISyncTask;
import com.tivic.manager.mob.processamento.sincronizacao.tasks.SyncTask;
import com.tivic.manager.mob.publicacao.edital.EditalPublicacaoService;
import com.tivic.manager.mob.publicacao.edital.IEditalPublicacaoService;
import com.tivic.manager.mob.radar.processamento.ProcessamentoService;
import com.tivic.manager.mob.relatorioestatisticas.GerarRelatorioEstatistico;
import com.tivic.manager.mob.relatorioestatisticas.IGerarRelatorioEstatistico;
import com.tivic.manager.mob.relatorioestatisticas.IRelatorioEstatisticasService;
import com.tivic.manager.mob.relatorioestatisticas.RelatorioEstatisticasService;
import com.tivic.manager.mob.restituicao.GerarRelatorioRestituicao;
import com.tivic.manager.mob.restituicao.IGerarRelatorioRestituicao;
import com.tivic.manager.mob.rrd.IRrdService;
import com.tivic.manager.mob.rrd.RrdRepository;
import com.tivic.manager.mob.rrd.RrdRepositoryDAO;
import com.tivic.manager.mob.rrd.RrdService;
import com.tivic.manager.mob.talonario.ITalonarioService;
import com.tivic.manager.mob.talonario.TalonarioRepository;
import com.tivic.manager.mob.talonario.TalonarioRepositoryDAO;
import com.tivic.manager.mob.talonario.TalonarioRepositoryFactory;
import com.tivic.manager.mob.talonario.TalonarioService;
import com.tivic.manager.mob.tipoevento.ITipoEventoService;
import com.tivic.manager.mob.tipoevento.TipoEventoRepository;
import com.tivic.manager.mob.tipoevento.TipoEventoRepositoryDAO;
import com.tivic.manager.mob.tipoevento.TipoEventoService;
import com.tivic.manager.mob.trrav.ITrravService;
import com.tivic.manager.mob.trrav.TrravRepository;
import com.tivic.manager.mob.trrav.TrravRepositoryDAO;
import com.tivic.manager.mob.trrav.TrravService;
import com.tivic.manager.mob.veiculosmultavencida.IVeiculosMultaVencidaService;
import com.tivic.manager.mob.veiculosmultavencida.VeiculosMultaVencidaService;
import com.tivic.manager.ptc.documento.DocumentoRepository;
import com.tivic.manager.ptc.documento.DocumentoRepositoryDAO;
import com.tivic.manager.ptc.documento.DocumentoService;
import com.tivic.manager.ptc.documento.IDocumentoService;
import com.tivic.manager.ptc.documentoocorrencia.DocumentoOcorrenciaService;
import com.tivic.manager.ptc.documentoocorrencia.IDocumentoOcorrenciaService;
import com.tivic.manager.ptc.documentopessoa.DocumentoPessoaRepository;
import com.tivic.manager.ptc.documentopessoa.DocumentoPessoaRepositoryDAO;
import com.tivic.manager.ptc.fase.FaseRepositoryDAO;
import com.tivic.manager.ptc.fase.FaseService;
import com.tivic.manager.ptc.fase.IFaseRepository;
import com.tivic.manager.ptc.fase.IFaseService;
import com.tivic.manager.ptc.fici.ApresentacaoCondutorRepository;
import com.tivic.manager.ptc.fici.ApresentacaoCondutorRepositoryDAO;
import com.tivic.manager.ptc.fici.ApresentacaoCondutorService;
import com.tivic.manager.ptc.fici.IApresentacaoCondutorService;
import com.tivic.manager.ptc.generators.GeraNumeroEdital;
import com.tivic.manager.ptc.generators.IGeraNumeroEdital;
import com.tivic.manager.ptc.portal.IPortalService;
import com.tivic.manager.ptc.portal.PortalService;
import com.tivic.manager.ptc.portal.baseantiga.IPortalNotificacoesService;
import com.tivic.manager.ptc.portal.baseantiga.PortalNotificacoesService;
import com.tivic.manager.ptc.portal.comprovante.ComprovanteService;
import com.tivic.manager.ptc.portal.comprovante.IComprovanteService;
import com.tivic.manager.ptc.portal.credencialestacionamento.CredencialEstacionamentoService;
import com.tivic.manager.ptc.portal.credencialestacionamento.ICredencialEstacionamentoService;
import com.tivic.manager.ptc.portal.impressaoait.AndamentoAitReport;
import com.tivic.manager.ptc.portal.impressaoait.IAndamentoAitReport;
import com.tivic.manager.ptc.portal.jari.cartajulgamento.GeraCartaJulgamentoJari;
import com.tivic.manager.ptc.portal.jari.cartajulgamento.IGeraCartaJulgamento;
import com.tivic.manager.ptc.protocolos.documentoarquivo.DocumentoArquivoRepository;
import com.tivic.manager.ptc.protocolos.documentoarquivo.DocumentoArquivoRepositoryDAO;
import com.tivic.manager.ptc.protocolos.documentoocorrencia.DocumentoOcorrenciaRepository;
import com.tivic.manager.ptc.protocolos.documentoocorrencia.DocumentoOcorrenciaRepositoryDAO;
import com.tivic.manager.ptc.protocolos.julgamento.CartaJulgamentoService;
import com.tivic.manager.ptc.protocolos.julgamento.ICartaJulgamentoService;
import com.tivic.manager.ptc.protocolos.relatorio.GerarBoletimDefesaAutuacao;
import com.tivic.manager.ptc.protocolos.relatorio.GerarFormularioCondutorProtocolo;
import com.tivic.manager.ptc.protocolos.relatorio.GerarFormularioDefesaProtocolo;
import com.tivic.manager.ptc.protocolos.relatorio.IGerarBoletimDefesaAutuacao;
import com.tivic.manager.ptc.protocolos.relatorio.IGerarFormularioCondutorProtocolo;
import com.tivic.manager.ptc.protocolos.relatorio.IGerarFormularioDefesaProtocolo;
import com.tivic.manager.ptc.protocolosv3.IProtocoloService;
import com.tivic.manager.ptc.protocolosv3.ProtocoloService;
import com.tivic.manager.ptc.protocolosv3.advertencia.DefesaAdvertenciaService;
import com.tivic.manager.ptc.protocolosv3.cetran.CetranService;
import com.tivic.manager.ptc.protocolosv3.documento.ata.AtaRelatorRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.documento.ata.AtaRelatorService;
import com.tivic.manager.ptc.protocolosv3.documento.ata.AtaRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.documento.ata.AtaService;
import com.tivic.manager.ptc.protocolosv3.documento.ata.IAtaRelatorRepository;
import com.tivic.manager.ptc.protocolosv3.documento.ata.IAtaRelatorService;
import com.tivic.manager.ptc.protocolosv3.documento.ata.IAtaRepository;
import com.tivic.manager.ptc.protocolosv3.documento.ata.IAtaService;
import com.tivic.manager.ptc.protocolosv3.documento.situacao.ISituacaoDocumentoRepository;
import com.tivic.manager.ptc.protocolosv3.documento.situacao.ISituacaoDocumentoService;
import com.tivic.manager.ptc.protocolosv3.documento.situacao.SituacaoDocumentoRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.documento.situacao.SituacaoDocumentoService;
import com.tivic.manager.ptc.protocolosv3.externo.IProtocoloExternoService;
import com.tivic.manager.ptc.protocolosv3.externo.ProtocoloExternoRepository;
import com.tivic.manager.ptc.protocolosv3.externo.ProtocoloExternoRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.externo.ProtocoloExternoService;
import com.tivic.manager.ptc.protocolosv3.externo.impressao.GeraImpressaoProtocoloExterno;
import com.tivic.manager.ptc.protocolosv3.externo.impressao.IGeraImpressaoProtocoloExterno;
import com.tivic.manager.ptc.protocolosv3.externo.oficio.GeraOficioProtocoloExterno;
import com.tivic.manager.ptc.protocolosv3.externo.oficio.IGeraOficioProtocoloExterno;
import com.tivic.manager.ptc.protocolosv3.jari.JariService;
import com.tivic.manager.ptc.protocolosv3.ocorrencia.IProtocoloOcorrenciaService;
import com.tivic.manager.ptc.protocolosv3.ocorrencia.ProtocoloOcorrenciaService;
import com.tivic.manager.ptc.protocolosv3.parecer.IParecerRepository;
import com.tivic.manager.ptc.protocolosv3.parecer.IParecerService;
import com.tivic.manager.ptc.protocolosv3.parecer.ParecerRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.parecer.ParecerService;
import com.tivic.manager.ptc.protocolosv3.parecer.relatorioparecer.IRelatorioParecerService;
import com.tivic.manager.ptc.protocolosv3.parecer.relatorioparecer.RelatorioParecerService;
import com.tivic.manager.ptc.protocolosv3.print.IProtocoloPrintService;
import com.tivic.manager.ptc.protocolosv3.print.ProtocoloPrintService;
import com.tivic.manager.ptc.protocolosv3.protocoloarquivos.IProtocoloArquivoService;
import com.tivic.manager.ptc.protocolosv3.protocoloarquivos.ProtocoloArquivoService;
import com.tivic.manager.ptc.protocolosv3.publicacao.IPublicacaoProtocoloService;
import com.tivic.manager.ptc.protocolosv3.publicacao.PublicacaoProtocoloService;
import com.tivic.manager.ptc.protocolosv3.recursos.IRecursoRepository;
import com.tivic.manager.ptc.protocolosv3.recursos.RecursoRepositoryDAO;
import com.tivic.manager.ptc.protocolosv3.resultado.IProtocoloResultadoService;
import com.tivic.manager.ptc.protocolosv3.resultado.ProtocoloResultadoService;
import com.tivic.manager.ptc.tipodocumento.ITipoDocumentoService;
import com.tivic.manager.ptc.tipodocumento.TipoDocumentoRepository;
import com.tivic.manager.ptc.tipodocumento.TipoDocumentoRepositoryDAO;
import com.tivic.manager.ptc.tipodocumento.TipoDocumentoService;
import com.tivic.manager.relatorios.estatisticasaits.EstatisticasAitsService;
import com.tivic.manager.relatorios.estatisticasaits.GeraRelatorioEstatisticasAits;
import com.tivic.manager.relatorios.estatisticasaits.IEstatisticasAitsService;
import com.tivic.manager.relatorios.estatisticasaits.IGeraRelatorioEstatisticasAits;
import com.tivic.manager.seg.usuario.IUsuarioPessoaService;
import com.tivic.manager.seg.usuario.UsuarioPessoaService;
import com.tivic.manager.seg.usuario.repositories.IUsuarioRepository;
import com.tivic.manager.str.MarcaModeloOldRepository;
import com.tivic.manager.str.MarcaModeloOldRepositoryDAO;
import com.tivic.manager.str.MarcaModeloStrRepository;
import com.tivic.manager.str.MarcaModeloStrRepositoryDAO;
import com.tivic.manager.str.endereco.EnderecoRepository;
import com.tivic.manager.str.endereco.EnderecoRepositoryDAO;
import com.tivic.manager.str.endereco.EnderecoService;
import com.tivic.manager.str.endereco.IEnderecoService;
import com.tivic.manager.str.endereco.enderecoboat.EnderecoBoatRepository;
import com.tivic.manager.str.endereco.enderecoboat.EnderecoBoatRepositoryDAO;
import com.tivic.manager.task.ITaskExecucao;
import com.tivic.manager.task.TaskExecucao;
import com.tivic.manager.tasks.limpeza.lotes.ILimpezaLotesService;
import com.tivic.manager.tasks.limpeza.lotes.LimpezaLotesService;
import com.tivic.manager.tasks.sincronizacao.tabelas.connections.ISincronizadorClient;
import com.tivic.manager.tasks.sincronizacao.tabelas.connections.ISincronizadorConnection;
import com.tivic.manager.tasks.sincronizacao.tabelas.connections.SincronizadorClient;
import com.tivic.manager.tasks.sincronizacao.tabelas.connections.SincronizadorConnection;
import com.tivic.manager.tasks.sincronizacao.tabelas.services.ITaskSincronizacaoTabelas;
import com.tivic.manager.tasks.sincronizacao.tabelas.services.TaskSincronizacaoTabelas;
import com.tivic.manager.triagem.ITriagemService;
import com.tivic.manager.triagem.TriagemService;
import com.tivic.manager.triagem.app.EstacionamentoAppSyncService;
import com.tivic.manager.triagem.app.IEstacionamentoAppSyncService;
import com.tivic.manager.triagem.repositories.EstacionamentoDigitalImagemRepository;
import com.tivic.manager.triagem.repositories.EventoEstacionamentoDigitalDetalhesRepository;
import com.tivic.manager.triagem.repositories.EventoEstacionamentoDigitalRepositoryDAO;
import com.tivic.manager.triagem.repositories.IEstacionamentoDigitalImagemRepository;
import com.tivic.manager.triagem.repositories.IEventoEstacionamentoDigitalDetalhesRepository;
import com.tivic.manager.triagem.repositories.IEventoEstacionamentoDigitalRepository;
import com.tivic.manager.triagem.services.IParametroTriagemService;
import com.tivic.manager.triagem.services.IUsuarioTriagem;
import com.tivic.manager.triagem.services.ParametroTriagemService;
import com.tivic.manager.triagem.services.UsuarioTriagemService;
import com.tivic.manager.triagem.services.arquivo.EventoArquivoEstacionamentoService;
import com.tivic.manager.triagem.services.arquivo.IEventoArquivoEstacionamentoService;
import com.tivic.manager.triagem.services.detalhes.EventoEstacionamentoDigitalDetalhesService;
import com.tivic.manager.triagem.services.detalhes.IEventoEstacionamentoDigitalDetalhesService;
import com.tivic.manager.triagem.services.eventos.EventoEstacionamentoService;
import com.tivic.manager.triagem.services.eventos.IEventoEstacionamentoService;
import com.tivic.manager.triagem.usecase.CapturaEstacionamentoObservacaoUseCase;
import com.tivic.manager.triagem.usecase.ConfirmarEstacionamentoUseCase;
import com.tivic.manager.triagem.usecase.RejeitarEstacionamentoUseCase;
import com.tivic.manager.util.ContextManager;
import com.tivic.manager.util.cdi.mob.config.LoteBeanConfig;
import com.tivic.manager.util.manipulatefiles.GenerateFile;
import com.tivic.manager.util.manipulatefiles.IGenerateFile;
import com.tivic.manager.util.manipulatefiles.IManipulateFolder;
import com.tivic.manager.util.manipulatefiles.ManipulateFolder;
import com.tivic.manager.wsdl.detran.mg.TabelasAuxiliaresMG;
import com.tivic.manager.wsdl.detran.mg.alterardatalimiterecurso.AlterarDataLimiteRecursoDadosEntradaFactory;
import com.tivic.manager.wsdl.detran.mg.alterardatalimiterecurso.IAlterarDataLimiteRecursoDadosEntradaFactory;
import com.tivic.manager.wsdl.detran.mg.soap.backup.Backup;
import com.tivic.manager.wsdl.detran.mg.soap.backup.GeradorArquivoBackup;
import com.tivic.manager.wsdl.interfaces.TabelasAuxiliares;
import com.tivic.sol.auth.AuthBase;
import com.tivic.sol.auth.AuthService;
import com.tivic.sol.auth.IAuthBase;
import com.tivic.sol.auth.IAuthService;
import com.tivic.sol.auth.ManagerUsers;
import com.tivic.sol.auth.jwt.JWT;
import com.tivic.sol.auth.password.GenerateMd5;
import com.tivic.sol.auth.password.GeneratePassword;
import com.tivic.sol.auth.password.NoneVerify;
import com.tivic.sol.auth.password.VerifyPassword;
import com.tivic.sol.auth.security.bruteforce.BruteForceProtection;
import com.tivic.sol.auth.usuario.IUsuarioService;
import com.tivic.sol.auth.usuario.UsuarioService;
import com.tivic.sol.auth.usuario.dao.UsuarioRepository;
import com.tivic.sol.auth.usuario.dao.UsuarioRepositoryFactory;
import com.tivic.sol.cdi.InjectBuilder;
import com.tivic.sol.cdi.Scope;
import com.tivic.sol.conf.Configuration;
import com.tivic.sol.conf.ConfigurationBuilder;
import com.tivic.sol.connection.creater.CreaterConnection;
import com.tivic.sol.connection.creater.CreaterConnectionConf;
import com.tivic.sol.files.pdf.IPdfGenerator;
import com.tivic.sol.files.pdf.PdfGenerator;
import com.tivic.sol.fix.FixRepository;
import com.tivic.sol.fix.FixRepositoryDAO;
import com.tivic.sol.fix.FixService;
import com.tivic.sol.fix.IFixService;
import com.tivic.sol.httpclient.ISolHttpClient;
import com.tivic.sol.httpclient.SolHttpClient;
import com.tivic.sol.log.ManagerLog;
import com.tivic.sol.log.ManagerLogBuilder;
import com.tivic.sol.permission.Permission;
import com.tivic.sol.permission.acao.AcaoRepository;
import com.tivic.sol.permission.acao.AcaoRepositoryDAO;
import com.tivic.sol.permission.acao.AcaoService;
import com.tivic.sol.permission.acao.IAcaoService;
import com.tivic.sol.permission.modulo.IModuloService;
import com.tivic.sol.permission.modulo.ModuloRepository;
import com.tivic.sol.permission.modulo.ModuloRepositoryDAO;
import com.tivic.sol.permission.modulo.ModuloService;
import com.tivic.sol.permission.usuariomodulo.IUsuarioModuloService;
import com.tivic.sol.permission.usuariomodulo.UsuarioModuloRepository;
import com.tivic.sol.permission.usuariomodulo.UsuarioModuloRepositoryDAO;
import com.tivic.sol.permission.usuariomodulo.UsuarioModuloService;
import com.tivic.sol.permission.usuariopermissaoacao.IUsuarioPermissaoAcaoService;
import com.tivic.sol.permission.usuariopermissaoacao.UsuarioPermissaoAcaoRepository;
import com.tivic.sol.permission.usuariopermissaoacao.UsuarioPermissaoAcaoRepositoryDAO;
import com.tivic.sol.permission.usuariopermissaoacao.UsuarioPermissaoAcaoService;
import com.tivic.sol.task.ITaskService;
import com.tivic.sol.task.TaskRepository;
import com.tivic.sol.task.TaskRepositoryDAO;
import com.tivic.sol.task.TaskService;

public class InjectApplicationBuilder implements InjectBuilder {

	public void build(Scope scope) throws Exception {
		buildTools(scope);
		buildAuth(scope);
		buildPermission(scope);
		buildRepository(scope);
		buildService(scope);
		LoteBeanConfig.inject(scope);
	}

	private void buildTools(Scope scope) throws Exception {
		scope.inject(ManagerLog.class, new ManagerLogBuilder()
				.confManager(ManagerConf.getInstance())
				.build());
		scope.inject(CreaterConnection.class, new CreaterConnectionConf());
		scope.inject(Configuration.class, new ConfigurationBuilder()
				.confManager(ManagerConf.getInstance())
				.realPath(ContextManager.getRealPath())
				.build());
		scope.inject(ISolHttpClient.class, new SolHttpClient());
		scope.inject(ISincronizadorConnection.class, new SincronizadorConnection());
		scope.inject(IAitSyncTools.class, new AitSyncTools());
	}

	private void buildAuth(Scope scope) throws Exception {
		scope.inject(VerifyPassword.class, new NoneVerify());
		scope.inject(GeneratePassword.class, new GenerateMd5());
		scope.inject(UsuarioRepository.class, new UsuarioRepositoryFactory().getStrategy());
		scope.inject(IUsuarioService.class, new UsuarioService());
		scope.inject(BruteForceProtection.class, new BruteForceProtection());
		scope.inject(JWT.class, new JWT());
		scope.inject(ManagerUsers.class, new ManagerUsers());
		scope.inject(IAuthBase.class, new AuthBase());
		scope.inject(IAuthService.class, new AuthService());
	}

	private void buildPermission(Scope scope) throws Exception {
		scope.inject(AcaoRepository.class, new AcaoRepositoryDAO());
		scope.inject(IAcaoService.class, new AcaoService());
		scope.inject(ModuloRepository.class, new ModuloRepositoryDAO());
		scope.inject(IModuloService.class, new ModuloService());
		scope.inject(UsuarioPermissaoAcaoRepository.class, new UsuarioPermissaoAcaoRepositoryDAO());
		scope.inject(IUsuarioPermissaoAcaoService.class, new UsuarioPermissaoAcaoService());
		scope.inject(UsuarioModuloRepository.class, new UsuarioModuloRepositoryDAO());
		scope.inject(IUsuarioModuloService.class, new UsuarioModuloService());
		scope.inject(Permission.class, new Permission());
	}

	private void buildRepository(Scope scope) throws Exception {
		scope.inject(IFileSystemRepository.class, new FileSystemRepository());
		scope.inject(IArquivoRepository.class, new ArquivoRepositoryDAO());
		scope.inject(IPessoaArquivoRepository.class, new PessoaArquivoRepository());
		scope.inject(ApresentacaoCondutorRepository.class, new ApresentacaoCondutorRepositoryDAO());
		scope.inject(DocumentoArquivoRepository.class, new DocumentoArquivoRepositoryDAO());
		scope.inject(AitRepository.class, new AitRepositoryFactory().getStrategy());
		scope.inject(AitPagamentoRepository.class, new AitPagamentoRepositoryDAO());
		scope.inject(AitMovimentoRepository.class, new AitMovimentoRepositoryFactory().getStrategy());
		scope.inject(AitMovimentoDocumentoRepository.class, new AitMovimentoDocumentoRepositoryDAO());
		scope.inject(ApresentacaoCondutorRepository.class, new ApresentacaoCondutorRepositoryDAO());
		scope.inject(DocumentoOcorrenciaRepository.class, new DocumentoOcorrenciaRepositoryDAO());
		scope.inject(DocumentoRepository.class, new DocumentoRepositoryDAO());
		scope.inject(ILoteImpressaoRepository.class, new LoteImpressaoFactory().getStrategy());
		scope.inject(ILoteImpressaoAitRepository.class, new LoteImpressaoAitRepositoryDAO());
		scope.inject(CorreiosLoteRepository.class, new CorreiosLoteRepositoryDAO());
		scope.inject(ICorreiosEtiquetaRepository.class, new CorreiosEtiquetaRepositoryDAO());
		scope.inject(TaskRepository.class, new TaskRepositoryDAO());
		scope.inject(DocumentoOcorrenciaRepository.class, new DocumentoOcorrenciaRepositoryDAO());
		scope.inject(IFaseRepository.class, new FaseRepositoryDAO());
		scope.inject(EquipamentoRepository.class, new EquipamentoRepositoryDAO());
		scope.inject(BoatRepository.class, new BoatRepositoryDAO());
		scope.inject(IFaseRepository.class, new FaseRepositoryDAO());
		scope.inject(IPessoaRepository.class, new PessoaRepositoryDAO());
		scope.inject(IPessoaFisicaRepository.class, new PessoaFisicaRepositoryDAO());
		scope.inject(IPessoaEnderecoRepository.class, new PessoaEnderecoRepositoryDAO());
		scope.inject(IPessoaEmpresaRepository.class, new PessoaEmpresaRepositoryDAO());
		scope.inject(FixRepository.class, new FixRepositoryDAO());
		scope.inject(InfracaoRepository.class, new InfracaoRepositoryFactory().getStrategy());
		scope.inject(AgenteRepository.class, new AgenteRepositoryFactory().getStrategy());
		scope.inject(CidadeRepository.class, new CidadeRepositoryDAO());
		scope.inject(EstadoRepository.class, new EstadoRepositoryDAO());
		scope.inject(PessoaRepository.class, new com.tivic.manager.mob.pessoa.PessoaRepositoryDAO());
		scope.inject(ArquivoMovimentoRepository.class, new ArquivoMovimentoRepositoryDAO());
		scope.inject(OcorrenciaRepository.class, new OcorrenciaRepositoryDAO());
		scope.inject(IAtaRepository.class, new AtaRepositoryDAO());
		scope.inject(IAtaRelatorRepository.class, new AtaRelatorRepositoryDAO());
		scope.inject(IRecursoRepository.class, new RecursoRepositoryDAO());
		scope.inject(ISituacaoDocumentoRepository.class, new SituacaoDocumentoRepositoryDAO());
		scope.inject(TipoDocumentoRepository.class, new TipoDocumentoRepositoryDAO());
		scope.inject(com.tivic.manager.gpn.tipodocumento.TipoDocumentoRepository.class, new com.tivic.manager.gpn.tipodocumento.TipoDocumentoRepositoryDAO());
		scope.inject(ILoteImpressaoArquivoRepository.class, new LoteImpressaoArquivoRepositoryDAO());
		scope.inject(InconsistenciaRepository.class, new InconsistenciaRepositoryDAO());
		scope.inject(AitInconsistenciaRepository.class, new AitInconsistenciaRepositoryDAO());
		scope.inject(TipoVeiculoRepository.class, new TipoVeiculoRepositoryDAO());
		scope.inject(PessoaJuridicaRepository.class, new PessoaJuridicaRepositoryDAO());
		scope.inject(OrgaoRepository.class, new OrgaoRepositoryDAO());
		scope.inject(MarcaModeloRepository.class, new MarcaModeloRepositoryDAO());
		scope.inject(EspecieVeiculoRepository.class, new EspecieVeiculoRepositoryDAO());
		scope.inject(PaisRepository.class, new PaisRepositoryDAO());
		scope.inject(ParametroValorRepository.class, new ParametroValorRepositoryDAO());
		scope.inject(InfracaoObservacaoRepository.class, new InfracaoObservacaoRepositoryDAO());
		scope.inject(TalonarioRepository.class, new TalonarioRepositoryDAO());
		scope.inject(com.tivic.manager.seg.usuario.repositories.UsuarioRepository.class,
				new com.tivic.manager.seg.usuario.repositories.UsuarioRepositoryDAO());
		scope.inject(IParametroRepository.class, new ParametroRepositoryDAOFactory().getStrategy());
		scope.inject(IAitImagemRepository.class, new AitImagemRepositoryFactory().getStrategy());
		scope.inject(AcaoUsuarioRepository.class, new AcaoUsuarioRepositoryDAO());
		scope.inject(BancoRepository.class, new BancoRepositoryDAO());
		scope.inject(ITermosECondicoesRepository.class, new TermosECondicoesRepositoryDAO());
		scope.inject(IParecerRepository.class, new ParecerRepositoryDAO());
		scope.inject(EventoEquipamentoRepository.class, new EventoEquipamentoRepositoryDAO());
		scope.inject(AitEventoRepository.class, new AitEventoRepositoryDAO());
		scope.inject(TalonarioRepository.class, new TalonarioRepositoryFactory().getStrategy());
		scope.inject(RrdRepository.class, new RrdRepositoryDAO());
		scope.inject(TrravRepository.class, new TrravRepositoryDAO());
		scope.inject(ProtocoloExternoRepository.class, new ProtocoloExternoRepositoryDAO());
		scope.inject(DocumentoPessoaRepository.class, new DocumentoPessoaRepositoryDAO());
		scope.inject(IUsuarioRepository.class, new com.tivic.manager.seg.usuario.repositories.UsuarioRepositoryFactory().getStrategy());
		scope.inject(MarcaModeloRepository.class, new MarcaModeloRepositoryDAO());
		scope.inject(EspecieVeiculoRepository.class, new EspecieVeiculoRepositoryDAO());
		scope.inject(CorRepository.class, new CorRepositoryDAO());
		scope.inject(EventoArquivoRepository.class, new EventoArquivoRepositoryDAO());
		scope.inject(AitPessoaRepository.class, new AitPessoaRepositoryDAO());
		scope.inject(AitImagemPessoaRepository.class, new AitImagemPessoaRepositoryDAO());
		scope.inject(TipoEventoRepository.class, new TipoEventoRepositoryDAO());
		scope.inject(IEventoEstacionamentoDigitalRepository.class, new EventoEstacionamentoDigitalRepositoryDAO());
		scope.inject(IEventoEstacionamentoDigitalDetalhesRepository.class, new EventoEstacionamentoDigitalDetalhesRepository());
		scope.inject(IEstacionamentoDigitalImagemRepository.class, new EstacionamentoDigitalImagemRepository());
		scope.inject(EventoArquivoRepository.class, new EventoArquivoRepositoryDAO());
		scope.inject(TipoEventoRepository.class, new TipoEventoRepositoryDAO());
		scope.inject(ConvenioRepository.class, new ConvenioRepositoryDAO());
		scope.inject(ITipoArquivoRepository.class, new TipoArquivoRepositoryDAO());
		scope.inject(IAitCancelamentoRepository.class, new AitCancelamentoRepositoryDAO());
		scope.inject(OrgaoExternoRepository.class, new OrgaoExternoRepositoryDAO());
		scope.inject(BairroRepository.class, new BairroRepositoryDAO());
		scope.inject(EnderecoRepository.class, new EnderecoRepositoryDAO());
		scope.inject(EnderecoBoatRepository.class, new EnderecoBoatRepositoryDAO());
		scope.inject(LoteRepository.class, new LoteRepositoryDAO());
		scope.inject(LoteDividaAtivaRepository.class, new LoteDividaAtivaRepositoryDAO());
		scope.inject(LoteDividaAtivaAitRepository.class, new LoteDividaAtivaAitRepositoryDAO());
		scope.inject(LoteDocumentoExternoRepository.class, new LoteDocumentoExternoRepositoryDAO());
		scope.inject(com.tivic.manager.mob.lotes.repository.arquivo.ArquivoRepository.class, new com.tivic.manager.mob.lotes.repository.arquivo.ArquivoRepositoryDAO());
		scope.inject(MarcaModeloOldRepository.class, new MarcaModeloOldRepositoryDAO());
		scope.inject(MarcaModeloStrRepository.class, new MarcaModeloStrRepositoryDAO());
		scope.inject(IAitArquivoRepository.class, new AitArquivoRepositoryDAO());
		scope.inject(VinculoRepository.class, new VinculoRepositoryDAO());
		scope.inject(PessoaVinculoHistoricoRepository.class, new PessoaVinculoHistoricoRepositoryDAO());
		scope.inject(OrgaoArquivoRepository.class, new OrgaoArquivoRepositoryDAO());
		scope.inject(CategoriaVeiculoRepository.class, new CategoriaVeiculoRepositoryDAO());
	}

	private void buildService(Scope scope) throws Exception {
		scope.inject(IEDatService.class, new EDatService());
		scope.inject(IBancoService.class, new BancoService());
		scope.inject(IFunsetService.class, new FunsetService());
		scope.inject(FunsetBuscaAits.class, new FunsetBuscaAits());
		scope.inject(FunsetInfos.class, new FunsetInfos());
		scope.inject(IAitMovimentoService.class, new AitMovimentoService());
		scope.inject(IAitService.class, new AitService());
		scope.inject(CircuitoAit.class, new CircuitoAit());
		scope.inject(IAitMovimentoService.class, new AitMovimentoService());
		scope.inject(IRelatorioRecursoServices.class, new RelatorioRecursoServices());
		scope.inject(AitMovimentoDocumentoServices.class, new AitMovimentoDocumentoServices());
		scope.inject(TabelasAuxiliares.class, new TabelasAuxiliaresMG());
		scope.inject(IPdfGenerator.class, new PdfGenerator());
		scope.inject(CorreiosEtiquetaServices.class, new CorreiosEtiquetaServices());
		scope.inject(IGeracaoDocumentosSSE.class, new GeracaoDocumentosSSE());
		scope.inject(IFTPSService.class, new FTPSService());
		scope.inject(ICorreiosEtiquetaService.class, new CorreiosEtiquetaService());
		scope.inject(ILoteNotificacaoService.class, new LoteNotificacaoService());
		scope.inject(ILoteDocumentoExternoService.class, new LoteDocumentoExternoService());
		scope.inject(IRelatorioAitCompetenciaEstadual.class, new RelatorioAitCompetenciaEstadual());
		scope.inject(AitReportServicesNip.class, new AitReportServicesNip());
		scope.inject(AitReportValidatorsNIP.class, new AitReportValidatorsNIP());
		scope.inject(ITaskService.class, new TaskService());
		scope.inject(IArquivoService.class, new ArquivoService());
		scope.inject(IAitMovimentoDocumentoService.class, new AitMovimentoDocumentoService());
		scope.inject(ICorreiosLoteService.class, new CorreiosLoteService());
		scope.inject(ILoteNotificacaoAitService.class, new LoteNotificacaoAitService());
		scope.inject(IImageReencoder.class, new ImageReencoder());
		scope.inject(ConversorBaseAntigaNovaFactory.class, new ConversorBaseAntigaNovaFactory());
		scope.inject(IClientConversorImagemTask.class, new ClientConversorImagemTask());
		scope.inject(IAitSyncObserver.class, new ImageConversionObserver());
		scope.inject(IAitSyncSubject.class, new AitSyncSubject());
		scope.inject(IAitImagemService.class, new AitImagemService());
		scope.inject(IOcorrenciaService.class, new OcorrenciaService());
		scope.inject(IFaseService.class, new FaseService());
		scope.inject(IEquipamentoService.class, new EquipamentoService());
		scope.inject(IApresentacaoCondutorService.class, new ApresentacaoCondutorService());
		scope.inject(IColaboradorService.class, new ColaboradorService());
		scope.inject(IVerificaInfracaoAdvertencia.class, new VerificaInfracaoAdvertencia());
		scope.inject(ITaskExecucao.class, new TaskExecucao());
		scope.inject(IClientNotificacaoTask.class, new ClientNotificacaoTask());
		scope.inject(IDocumentoService.class, new DocumentoService());
		scope.inject(IPessoaEmpresaService.class, new PessoaEmpresaService());
		scope.inject(IUsuarioPessoaService.class, new UsuarioPessoaService());
		scope.inject(IFixService.class, new FixService());
		scope.inject(IManipulateFolder.class, new ManipulateFolder());
		scope.inject(IGenerateFile.class, new GenerateFile());
		scope.inject(IGerarFormularioCondutorProtocolo.class, new GerarFormularioCondutorProtocolo());
		scope.inject(IGerarFormularioDefesaProtocolo.class, new GerarFormularioDefesaProtocolo());
		scope.inject(IInfracaoService.class, new InfracaoService());
		scope.inject(IAgenteService.class, new AgenteService());
		scope.inject(Backup.class, new GeradorArquivoBackup());
		scope.inject(IAlterarDataLimiteRecursoDadosEntradaFactory.class,
				new AlterarDataLimiteRecursoDadosEntradaFactory());
		scope.inject(IAtaRelatorService.class, new AtaRelatorService());
		scope.inject(IAtaService.class, new AtaService());
		scope.inject(ICartaJulgamentoService.class, new CartaJulgamentoService());
		scope.inject(IProtocoloService.class, new ProtocoloService());
		scope.inject(ITipoDocumentoService.class, new TipoDocumentoService());
		scope.inject(IProtocoloArquivoService.class, new ProtocoloArquivoService());
		scope.inject(IAitInconsistenciaService.class, new AitInconsistenciaService());
		scope.inject(IInconsistenciaService.class, new InconsistenciaService());
		scope.inject(com.tivic.manager.ptc.protocolosv3.apresentacaocondutor.ApresentacaoCondutorService.class,
				new com.tivic.manager.ptc.protocolosv3.apresentacaocondutor.ApresentacaoCondutorService());
		scope.inject(IProtocoloResultadoService.class, new ProtocoloResultadoService());
		scope.inject(IProtocoloOcorrenciaService.class, new ProtocoloOcorrenciaService());
		scope.inject(JariService.class, new JariService());
		scope.inject(CetranService.class, new CetranService());
		scope.inject(IEditalPublicacaoService.class, new EditalPublicacaoService());
		scope.inject(IPublicacaoProtocoloService.class, new PublicacaoProtocoloService());
		scope.inject(ISituacaoDocumentoService.class, new SituacaoDocumentoService());
		scope.inject(IPublicacaoNotificacaoService.class, new PublicacaoNotificacaoService());
		scope.inject(IOrgaoService.class, new OrgaoService());
		scope.inject(DefesaAdvertenciaService.class, new DefesaAdvertenciaService());
		scope.inject(IClientPublicacaoNotificacaoTask.class, new ClientPublicacaoNotificacaoTask());
		scope.inject(IClientPublicacaoJariTask.class, new ClientPublicacaoJariTask());
		scope.inject(IClientEnvioRegistroInfracaoTask.class, new ClientEnvioRegistroInfracaoTask());
		scope.inject(IRealizaPagamento.class, new RealizaPagamento());
		scope.inject(IArquivoRetornoServiceEDI.class, new ArquivoRetornoServiceEDI());
		scope.inject(IAtualizaLoteImpressaoECT.class, new AtualizaLoteImpressaoECT());
		scope.inject(IArquivoProducaoServiceEDI.class, new ArquivoProducaoServiceEDI());
		scope.inject(IArquivoServiceEDI.class, new ArquivoServiceEDI());
		scope.inject(IEcartasService.class, new ECartasService());
		scope.inject(IDadosNotificacaoService.class, new DadosNotificacaoFactory().getStrategy());
		scope.inject(IComprovanteService.class, new ComprovanteService());
		scope.inject(IAndamentoAitReport.class, new AndamentoAitReport());
		scope.inject(ICredencialEstacionamentoService.class, new CredencialEstacionamentoService());
		scope.inject(IPortalService.class, new PortalService());
		scope.inject(ITalonarioService.class, new TalonarioService());
		scope.inject(IAitPagamentoService.class, new AitPagamentoService());
		scope.inject(IGeraRelatorioAitSne.class, new GeraRelatorioAitSne());
		scope.inject(IInfracaoObservacaoService.class, new InfracaoObservacaoService());
		scope.inject(IAcaoUsuarioService.class, new AcaoUsuarioService());
		scope.inject(ITermosECondicoesService.class, new TermosECondicoesService());
		scope.inject(ICorretorIDCidade.class, new CorretorIDCidade());
		scope.inject(IParametroService.class, new ParametroService());
		scope.inject(IProtocoloPrintService.class, new ProtocoloPrintService());
		scope.inject(IGerarBoletimDefesaAutuacao.class, new GerarBoletimDefesaAutuacao());
		scope.inject(ISincronizadorClient.class, new SincronizadorClient());
		scope.inject(ITaskSincronizacaoTabelas.class, new TaskSincronizacaoTabelas());
		scope.inject(IDocumentoOcorrenciaService.class, new DocumentoOcorrenciaService());
		scope.inject(IParecerService.class, new ParecerService());
		scope.inject(ITalonarioService.class, new TalonarioService());
		scope.inject(IRrdService.class, new RrdService());
		scope.inject(ITrravService.class, new TrravService());
		scope.inject(IProtocoloExternoService.class, new ProtocoloExternoService());
		scope.inject(IGeraImpressaoProtocoloExterno.class, new GeraImpressaoProtocoloExterno());
		scope.inject(IGeraCartaJulgamento.class, new GeraCartaJulgamentoJari());
		scope.inject(IPortalNotificacoesService.class, new PortalNotificacoesService());
		scope.inject(IGeraOficioProtocoloExterno.class, new GeraOficioProtocoloExterno());
		scope.inject(IParametroTriagemService.class, new ParametroTriagemService());
		scope.inject(IUsuarioTriagem.class, new UsuarioTriagemService());
		scope.inject(IMarcaModeloService.class, new MarcaModeloService());
		scope.inject(IEspecieVeiculoService.class, new EspecieVeiculoService());
		scope.inject(ICorService.class, new CorService());
		scope.inject(IEventoArquivoService.class, new EventoArquivoService());
		scope.inject(IAitEventoService.class, new AitEventoService());
		scope.inject(IEventoEquipamentoService.class, new EventoEquipamentoService());
		scope.inject(IConversorEventoService.class, new ConversorEventoService());
		scope.inject(IConversaoEventoService.class, new ConversaoEventoService());
		scope.inject(IAitPessoaService.class, new AitPessoaService());
		scope.inject(IAitImagemPessoaService.class, new AitImagemPessoaService());
		scope.inject(ITriagemService.class, new TriagemService());
		scope.inject(IEstacionamentoAppSyncService.class, new EstacionamentoAppSyncService());
		scope.inject(IEventoEstacionamentoService.class, new EventoEstacionamentoService());
		scope.inject(IEventoArquivoEstacionamentoService.class, new EventoArquivoEstacionamentoService());
		scope.inject(ITipoEventoService.class, new TipoEventoService());
		scope.inject(IEventoArquivoService.class, new EventoArquivoService());
		scope.inject(IEventoRadarHandlerService.class, new EventoRadarHandlerService());
		scope.inject(ISincronizacaoService.class, new SincronizacaoService());
		scope.inject(ISyncTask.class, new SyncTask());
		scope.inject(IConversaoEventosTask.class, new ConversaoEventosTask());
		scope.inject(ProcessamentoService.class, new ProcessamentoService());
		scope.inject(IGeraArquivoDividaAtiva.class, new GeraArquivoDividaAtiva());		
		scope.inject(IGeraLoteDividaAtiva.class, new GeraLoteDividaAtiva());
		scope.inject(IConfirmaLoteDividaAtiva.class, new ConfirmaLoteDividaAtiva());
		scope.inject(ILoteDividaAtivaService.class, new LoteDividaAtivaService());
		scope.inject(IOrgaoExternoService.class, new OrgaoExternoService());
		scope.inject(ICidadeService.class, new CidadeService());
		scope.inject(IFixProprietarioAitService.class, new FixProprietarioAitService());
		scope.inject(ILimpezaLotesService.class, new LimpezaLotesService());
		scope.inject(IAtualizaTalonarioAitPessoa.class, new AtualizaTalonarioAitPessoa());
		scope.inject(IAtualizaTalonarioAit.class, new AtualizaTalonarioAit());
		scope.inject(IAitSyncService.class, new AitSyncService());
		scope.inject(IAitPessoaSyncService.class, new AitPessoaSyncService());
		scope.inject(IFixInfracaoAitService.class, new FixInfracaoAitService());
		scope.inject(IMudaConvenioDefault.class, new MudaConvenioDefault());
		scope.inject(IConvenioService.class, new ConvenioService());
		scope.inject(ITipoArquivoService.class, new TipoArquivoService());
		scope.inject(IRadarService.class, new RadarService());
		scope.inject(IRelatorioQuantitativoService.class, new RelatorioQuantitativoService());
		scope.inject(IEnderecoService.class, new EnderecoService());
		scope.inject(IFixCidadeService.class, new FixCidadeService());
		scope.inject(IGuiaPagamentoService.class, new GuiaPagamentoService());
		scope.inject(IGeraGuiaPagamento.class, new GeraGuiaPagamento());
		scope.inject(IClientFixEnderecoNotificacao.class, new ClientFixEnderecoNotificacao());
		scope.inject(IValidacaoAitPendente.class, new ValidacaoAitPendente());
		scope.inject(IGeraSegundaViaNaiService.class, new GeraSegundaViaNaiService());
		scope.inject(IRelatorioParecerService.class, new RelatorioParecerService());
		scope.inject(ICancelaRevertePenalidade.class, new CancelaRevertePenalidade());
		scope.inject(com.tivic.manager.seg.usuario.IUsuarioService.class, new com.tivic.manager.seg.usuario.UsuarioService());
		scope.inject(IClientGeracaoNicTask.class, new ClientGeracaoNicTask());
		scope.inject(IAitVideoService.class, new AitVideoService());
		scope.inject(com.tivic.manager.mob.ait.imagemvideo.aitimagem.IAitImagemService.class, new com.tivic.manager.mob.ait.imagemvideo.aitimagem.AitImagemService());
		scope.inject(IRelatorioEstatisticasService.class, new RelatorioEstatisticasService());
		scope.inject(IGerarRelatorioEstatistico.class, new GerarRelatorioEstatistico());
		scope.inject(ICalculoMediaMovimentoService.class, new CalculoMediaMovimentoService());
		scope.inject(IEquipamentoTalonarioService.class, new EquipamentoTalonarioService());
		scope.inject(IGerarRelatorioRestituicao.class, new GerarRelatorioRestituicao());
		scope.inject(ITipoVeiculoService.class, new TipoVeiculoService());
		scope.inject(IEstatisticasAitsService.class, new EstatisticasAitsService());
		scope.inject(IVeiculosMultaVencidaService.class, new VeiculosMultaVencidaService());
		scope.inject(IListagemPagamentosService.class, new ListagemPagamentosService());
		scope.inject(IGeraRelatorioListagemPagamentos.class, new GeraRelatorioListagemPagamentos());
		scope.inject(IGeraRelatorioEstatisticasAits.class, new GeraRelatorioEstatisticasAits());
		scope.inject(IGeraNumeroEdital.class, new GeraNumeroEdital());
		scope.inject(IPessoaVinculoHistoricoService.class, new PessoaVinculoHistoricoService());
		scope.inject(IVinculoService.class, new VinculoService());
		scope.inject(IPessoaFisicaService.class, new PessoaFisicaService());
		scope.inject(IEventoEstacionamentoDigitalDetalhesService.class, new EventoEstacionamentoDigitalDetalhesService());
		scope.inject(IArquivoMovimentoService.class, new ArquivoMovimentoService());
		scope.inject(IOrgaoArquivoService.class, new OrgaoArquivoService());
		scope.inject(ConfirmarEstacionamentoUseCase.class, new ConfirmarEstacionamentoUseCase());
		scope.inject(RejeitarEstacionamentoUseCase.class, new RejeitarEstacionamentoUseCase());
		scope.inject(CapturaEstacionamentoObservacaoUseCase.class, new CapturaEstacionamentoObservacaoUseCase());
		scope.inject(CidadeOrgaoResolver.class, new CidadeOrgaoResolver());
	}
}