# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Build do projeto com Apache Ant

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Ant
        run: |
          # Executa o build e salva a saída em um arquivo
          ant -noinput -buildfile build.xml -lib web/WEB-INF/lib/ecj-4.6.1.jar clean build | tee build_output.log

          # Verifica se há erros de compilação na saída
          if grep -q "ERROR in" build_output.log; then
            echo "::error::Foram encontrados erros de compilação. Build falhou!"
            echo "Erros encontrados:"
            grep -A1 "ERROR in" build_output.log
            exit 1
          fi
